Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - VPC
        - EKS
    VPC:
      Type: AWS::EC2::VPC
      Direction: vertical
      Children:
        - VPCPublicStack
        - VPCPrivateStack
    VPCPublicStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPublicSubnet1
        - VPCPublicSubnet2
    VPCPublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
    VPCPublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
    VPCPrivateStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPrivateSubnet1
        - VPCPrivateSubnet2
    VPCPrivateSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
    VPCPrivateSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
    EKS:
      Type: AWS::EKS::Cluster
      Direction: vertical
      Children:
        - EKSNode1
        - EKSNode2
    EKSNode1:
      Type: AWS::Diagram::Resource
      Preset: EC2Instance
    EKSNode2:
      Type: AWS::Diagram::Resource
      Preset: EC2Instance
    ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: Application Load Balancer
    IGW:
      Type: AWS::EC2::InternetGateway
    User:
      Type: AWS::Diagram::Resource
      Preset: User

  Links:
    - Source: ALB
      SourcePosition: NNW
      Target: VPCPublicSubnet1
      TargetPosition: SSE
      TargetArrowHead:
        Type: Open
    - Source: ALB
      SourcePosition: NNE
      Target: VPCPublicSubnet2
      TargetPosition: SSW
      TargetArrowHead:
        Type: Open
    - Source: IGW
      SourcePosition: N
      Target: ALB
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: User
      SourcePosition: N
      Target: IGW
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: EKSNode1
      SourcePosition: W
      Target: VPCPrivateSubnet1
      TargetPosition: E
      TargetArrowHead:
        Type: Open
    - Source: EKSNode2
      SourcePosition: E
      Target: VPCPrivateSubnet2
      TargetPosition: W
      TargetArrowHead:
        Type: Open