Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - VPC
    VPC:
      Type: AWS::EC2::VPC
      Direction: horizontal
      Children:
        - CognitoStack
        - APIGatewayStack
        - DynamoDBStack
    CognitoStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - Cognito
    Cognito:
      Type: AWS::Cognito::UserPool
      Preset: User Pool
    APIGatewayStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - APIGateway
        - Lambda
    APIGateway:
      Type: AWS::ApiGateway::RestApi
      Preset: API Gateway
    Lambda:
      Type: AWS::Lambda::Function
      Preset: Lambda
    DynamoDBStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - DynamoDB
    DynamoDB:
      Type: AWS::DynamoDB::Table
      Preset: DynamoDB

    User:
      Type: AWS::Diagram::Resource
      Preset: User

  Links:
    - Source: User
      SourcePosition: N
      Target: Cognito
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: Cognito
      SourcePosition: E
      Target: APIGateway
      TargetPosition: W
      TargetArrowHead:
        Type: Open
    - Source: APIGateway
      SourcePosition: E
      Target: Lambda
      TargetPosition: W
      TargetArrowHead:
        Type: Open
    - Source: Lambda
      SourcePosition: E
      Target: DynamoDB
      TargetPosition: W
      TargetArrowHead:
        Type: Open