apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-architect-app
  labels:
    app: aws-architect-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aws-architect-app
  template:
    metadata:
      labels:
        app: aws-architect-app
    spec:
      containers:
      - name: aws-architect-app
        image: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/aws-architect-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "us-west-2"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: aws-architect-app-service
spec:
  selector:
    app: aws-architect-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
